### ISSUE TITLE
AmpedT plugin

### ISSUE THREAD

**Issue by Ramon-Fernando** [lrfasd/lrfasd.github.io#8]
Hello! I read this very interesting tutorial https://www.bilibili.com/read/cv17980427?from=articleDetail . I saw that the AmpedT plugins are not public. I'd like to know if i can get these plugins or how i can get them. Is there a way that i can get them? It's difficult to search for skins.
Thanks in advance!

**Comment by lrfasd** [comment]
see https://lrfasd.github.io/ampedT/

**Comment by muhammadfarhan26** [comment]
I saw the internal ampedT release, is it possible for people outside of China to access the plugin? because i don't have a fenchuan8 account. I've been following this repository for a long time and wish I could access the plugin. 
Thank you for any kind of help!

我看到了内部的 ampedT 版本，中国以外的人可以访问该插件吗？ 因为我没有fenchuan8帐号。 我已经关注这个存储库很长时间了，希望我可以访问该插件。
感谢您提供任何帮助！
